### PR TITLE
Add LCG generator (based on PCG)

### PR DESCRIPTION
**Pull request by dhardy**
As requested

### CODE REVIEW

**Comment by dhardy** [comment]
I've been trying to test some constructions, and noticed that `Pcg32x4` fails PractRand immediately (though 32x2 is fine for 1GB at least). Have you looked into this?

**Comment by TheIronBorn** [comment]
I haven’t noticed fialures like that for other PRNGs. Though I haven’t been looking for them. 

This might be stream correlation (perhaps even worse with a raw LCG).

**Comment by dhardy** [comment]
Considering both the increment and the initial state are randomised it seems a bit weird.

I don't know how you've been testing; I added a `Generate<T>` trait and tried adapting a semi-generic `cat-rng` script I wrote before (appears I didn't publish) but gave up.

**Comment by TheIronBorn** [comment]
I’ll add my `cat_rng.rs` implementation.

**Comment by TheIronBorn** [comment]
Yes, I am seeing `Pcg32x4` failing immediately at 256 megabytes.

(`cat_rng.rs` here https://github.com/TheIronBorn/simd_prngs/blob/master/src/bin/cat_rng.rs)

**Comment by TheIronBorn** [comment]
I'm not seeing other PRNGs do this. Odd

**Comment by dhardy** [comment]
Maybe check it does produce the same results as four interleaved instances (with fixed seeds)?

**Comment by TheIronBorn** [comment]
Ah, I got the rotate wrong.

**Pull request merged**
